# Generated by Django 5.2.7 on 2025-11-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='MARKETING', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('header_type', models.CharField(default='none', max_length=20)),
                ('header_text', models.TextField(blank=True, null=True)),
                ('body_text', models.TextField()),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
