# Generated by Django 5.2.8 on 2025-11-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('source', models.CharField(default='Manual', max_length=50)),
                ('lead_stage', models.CharField(default='New Lead', max_length=50)),
                ('allow_broadcast', models.BooleanField(default=True)),
                ('allow_sms', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
