# Generated by Django 5.2.7 on 2025-11-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team_user_teammembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_by',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
