# Generated by Django 5.2.7 on 2025-11-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_auth_user_remove_team_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convixuser',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
