# Generated by Django 5.2.7 on 2025-12-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='template',
            name='buttons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], default='MARKETING', max_length=20),
        ),
        migrations.AlterField(
            model_name='template',
            name='footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='header_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
    ]
