# Generated by Django 5.2.7 on 2026-01-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='flow',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
