# Generated by Django 5.2.7 on 2025-12-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='to_phone',
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='from_phone',
            field=models.CharField(max_length=30),
        ),
    ]
